baseurl                = "localhost"
title                  = "le-reseau.tech"
languageCode           = "fr-fr"
defaultContentLanguage = "fr"
theme                  = "hello-friend-ng"
paginate               = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "La french tech 0 bullshit"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "frenchtech community"
  keywords = "homepage, frenchtech"
  images = [""]

  [[params.social]]
    name = "discord"
    url = "https://discord.gg/JKVkhCeuPs"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.fr]
    title = "le-reseau.tech"
    subtitle = "Communauté tech francophone"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.fr.params.logo]
      logoText = "Bienvenue dans le réseau"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "discord"
    name       = "Discord"
    url        = "https://discord.gg/JKVkhCeuPs"
  [[menu.main]]
    identifier = "a-propos"
    name       = "A propos"
    url        = "/a-propos"
